pub mod context;
mod eq_decl;
pub mod equation;
pub mod oper;
mod oper_decl;
pub mod term;
mod theory;
pub mod r#type;
mod type_decl;
mod schema;
mod fkey_decl;
mod attr_decl;
mod theory_decl;
pub const DIRECTIVE_SIGN: &'static str = "#";
